import type { ThemeConfig } from './types'

export const spacing: ThemeConfig['spacing'] = {
  '2xl': 'var(--spacing-2xl, --margin-2xl)',
  '3xl': 'var(--spacing-3xl, --margin-3xl)',
  '4xl': 'var(--spacing-4xl, --margin-4xl)',
  '5xl': 'var(--spacing-5xl, --margin-5xl)',
  buttonLgX: 'var(--button-spacing-lg-x)',
  buttonLgY: 'var(--button-spacing-lg-y)',
  buttonSmX: 'var(--button-spacing-sm-x)',
  buttonSmY: 'var(--button-spacing-sm-y)',
  buttonX: 'var(--button-spacing-base-x)',
  buttonXlX: 'var(--button-spacing-xl-x)',
  buttonXlY: 'var(--button-spacing-xl-y)',
  buttonXsX: 'var(--button-spacing-xs-x)',
  buttonXsY: 'var(--button-spacing-xs-y)',
  buttonY: 'var(--button-spacing-base-y)',
  lg: 'var(--spacing-lg, --margin-lg)',
  md: 'var(--spacing-md, --margin-md)',
  none: 'var(--spacing-none, --margin-none)',
  sm: 'var(--spacing-sm, --margin-sm)',
  textSpacing: 'var(--text-spacing-base)',
  textSpacing2xl: 'var(--text-spacing-2xl)',
  textSpacingLg: 'var(--text-spacing-lg)',
  textSpacingNone: 'var(--text-spacing-none)',
  textSpacingSm: 'var(--text-spacing-sm)',
  textSpacingXl: 'var(--text-spacing-xl)',
  xl: 'var(--spacing-xl, --margin-xl)',
  xs: 'var(--spacing-xs, --margin-xs)',
}

export const borderRadius: ThemeConfig['borderRadius'] = {
  button: 'var(--button-border-radius)',
  buttonMd: 'var(--button-border-radius-md)',
  buttonNone: 'var(--button-border-radius-none)',
  buttonSm: 'var(--button-border-radius-sm)',
  form: 'var(--form-border-radius)',
  lg: 'var(--radius-lg)',
  md: 'var(--radius-md)',
  sm: 'var(--radius-sm)',
  xl: 'var(--radius-xl)',
  xs: 'var(--radius-xs)',
  xxs: 'var(--radius-xxs)',
}
